services:
  postgres:
    image: postgres:15
    container_name: savewise-db
    restart: always
    environment:
        POSTGRES_DB: SaveWise
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1111
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data

  savewisenew:
    image: ${DOCKER_REGISTRY-}savewisenew
    build:
      context: .
      dockerfile: SaveWiseNew/Dockerfile
    container_name: savewise-api
    environment:
      - ConnectionStrings__Db=Server=postgres;Port=5432;Database=SaveWise;User Id=postgres;Password=1111;
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres

volumes:
  postgres_data:

